### ISSUE TITLE
force option is not functional

### ISSUE THREAD

**Issue by vchepkov** [tkishel/pe_tune#8]
tune.rb ignores `--force` option in PE2018.1.9 and in pe_tune v2.4.1

```
# puppet infrastructure tune --force
# Puppet Infrastructure Summary: Found a Monolithic Infrastructure

Error: replica.localdomain does not meet the minimum system requirements to optimize its settings
```

furthermore, pe_tune actually fails:
```
# puppet pe tune --force --modulepath=~/modules
# Puppet Infrastructure Summary: Found a Monolithic Infrastructure

Error: undefined method `empty?' for nil:NilClass
Error: Try 'puppet help pe tune' for usage
```

FWIW, it works in version 2.3.0

**Comment by tkishel** [comment]
Thanks.

Tune will also return that error if a calculation returns an invalid value.
I should differentiate the errors.

Could you post (or email) output when run with ‘—debug’ ?
-- 
Tom Kishel

Senior Support Engineer
tom.kishel@puppet.com
Puppet. The shortest path to better software.

**Comment by tkishel** [comment]
'--debug' shows:

Error: available_ram_for_puppetserver: 205 < minimum_ram_puppetserver: 512

Below a certain threshold, using '--force' may result in unstable/unusable settings.

I've updated the 'minimum system requirements' error to always suggest '--debug' and I've improved the coverage and details when debugging.

**Comment by vchepkov** [comment]
Oh, minimum is 8G now? that makes it difficult to run master and node in Vagrant environment, hmm. Well, what can we do ¯\_(ツ)_/¯

**Comment by RandellP** [comment]
8gb has been the production min for a while I think.  We did support 6gb for trail use only for a while.  But with ACE and bolt server and the new orchestrator JVM... that is probably getting too tight.  of course force should let you try if it can generate a workable set of settings... sounds like it couldn't though.

**Comment by tkishel** [comment]
The tune (with --force) command is tested down to 2 Cores and 6 GB of RAM.
Could you provide the output of `facter processors memory` ?

**Comment by vchepkov** [comment]
I was trying with 4G VM. I will try 6G.

**Comment by tkishel** [comment]
Yes, below 2/6 the math is suspect, as it is untested.

I've updated the code to:

Output one warning if a node is below the minimum system requirements.
Output a different warning if the results are below the minimum for a service.
Warn instead of exit on the first node to not meet minimum requirements.

Okay to close?

**Comment by vchepkov** [comment]
Yes, thank you. 
FYI. PE still works with 2/4, I haven't seen any issues. 2/6 makes pe_tune work as well
